### ISSUE TITLE
Update to ASP Identity 2.2 and ASP MVC 5

### ISSUE THREAD

**Issue by weedkiller** [mark-j/DapperIdentityDemo#1]
Hi, can you please update this to the current identity 2.2 and ASP MVC 4.52

thanks

**Comment by mark-j** [comment]
@weedkiller I don't have any plans to update this to Identity 2.2 but I did just publish a new version for ASP.NET Core Identity 2.0, which is current as of now.

https://github.com/mark-j/dapper-identity

If you need ASP.NET Identity 2.2 support feel free to send a PR and I'll be happy to pull it in!

**Comment by weedkiller** [comment]
Any chance you can update to 2.2, with some properties like tenantID for user, and roles text description.

Right now its very limited. would like to see an update
